# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Stunt Shield API CI/CD

on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        
      - name: Install dependencies
        run: npm install

      # - name: Run unit tests
      #   run: npm test 

      - name: Build application
        run: npm run build

      - name: Deploy to Render
        run: |
          curl GET "https://api.render.com/deploy/${{ secrets.RENDER_API_KEY }}"
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}